[package]
name = "tetched-math"
version = "1.0.0"
authors = ['GalacticCouncil']
edition = "2018"

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}

[features]
default = ["std"]
std = []
